name: qr_example
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  bloc: ^8.1.0
  equatable: ^2.0.5
  freezed: 2.3.2
  freezed_annotation: 2.2.0
  cached_network_image: ^3.2.3
  flutter_screenutil: ^5.7.0
  qr_code_scanner: ^1.0.1
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  rolling_bottom_bar: ^0.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: 6.6.1
  build_runner: ^2.3.3

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/products.json
